#!/usr/bin/env python3
"""Generate a messages.h header for MD_Parola scrolling banners.

Usage:
    python tools/make_banner.py "Hello" "Another" > messages.h
"""

import argparse
from pathlib import Path

HEADER_GUARD = "// Auto-generated by tools/make_banner.py\n// Re-run the script to change messages.\n"


def escape_literal(text: str) -> str:
    """Escape backslashes and quotes for safe C string literals."""
    return text.replace("\\", "\\\\").replace("\"", "\\\"")


def build_header(messages, speed: int, intensity: int) -> str:
    lines = [HEADER_GUARD, "#pragma once\n", "#include <Arduino.h>\n", "// Scrolling parameters\n"]
    lines.append(f"constexpr uint8_t SCROLL_SPEED = {speed};\n")
    lines.append(f"constexpr uint8_t DISPLAY_INTENSITY = {intensity};\n\n")
    lines.append("// Messages displayed by the Arduino sketch\n")
    lines.append("static const char* const messages[] PROGMEM = {\n")
    for msg in messages:
        safe = escape_literal(msg)
        lines.append(f"  \"{safe}\",\n")
    lines.append("};\n")
    lines.append("constexpr uint8_t MESSAGE_COUNT = sizeof(messages) / sizeof(messages[0]);\n")
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate messages.h for MD_Parola")
    parser.add_argument("messages", nargs="+", help="Messages to display in order")
    parser.add_argument("--speed", type=int, default=40, help="Scroll speed value passed to MD_Parola (default: 40)")
    parser.add_argument("--intensity", type=int, default=2, help="Brightness 0-15 (default: 2)")
    args = parser.parse_args()

    header = build_header(args.messages, speed=args.speed, intensity=args.intensity)
    Path("messages.h").write_text(header, encoding="utf-8")
    print(header, end="")


if __name__ == "__main__":
    main()
